### ISSUE TITLE
g2p incorrectly expects top-level `language_name` key in config.yaml with multiple mappings

### ISSUE THREAD

**Issue by dhdaines** [roedoejet/g2p#181]
Currently, the `config.yaml` format described at https://blog.mothertongues.org/g2p-basic-mappings-local/ will cause g2p to fail with a confusing exception after running `g2p update`, e.g. a `config.yaml` like this will "work" when run with `g2p --config config.yaml` but will break g2p if installed inside `g2p/mappings/langs`:

```
mappings:
  - language_name: My Test Language # this is a shared value for all the mappings in this configuration
    display_name: My Test Language to IPA # this is a 'display name'. It is a user-friendly name for your mapping.
    in_lang: test # This is the code for your language input. By convention in g2p this should contain your language's ISO 639-3 code
    out_lang: test-ipa # This is the code for the output of your mapping. By convention in g2p we suffix -ipa to the in_lang for mappings between an orthography and IPA
    type: mapping 
    authors: # This is a way to keep track of who has contributed to the mapping
      - Aidan Pine
    mapping: test_to_ipa.json # This is the path to your mapping file. It should be in the same folder as your config.yaml file
```

This is because the code here https://github.com/roedoejet/g2p/blob/master/g2p/mappings/langs/__init__.py#L62 incorrectly assumes that the `language_name` key always exists at the top level of each configuration, even though it should be defined for each mapping.

This was fine when we had a single mapping at the top level of each `config.yaml`, and indeed, a `config.yaml` with a single mapping defined at the top level will still work, as confirmed here: https://github.com/roedoejet/g2p/blob/master/g2p/tests/test_z_local_config.py#L65

This is fixed by https://github.com/roedoejet/g2p/pull/179
