### ISSUE TITLE
`g2p generate-mapping` generates incorrect configuration

### ISSUE THREAD

**Issue by dhdaines** [roedoejet/g2p#354]
When running `g2p generate-mapping` for the first time, the filename in `g2p/mappings/langs/generated/config-g2p.yaml` is incorrect.  For instance when I create `g2p/mappings/langs/myh/config-g2p.yaml`:
```yaml
mappings:
  - display_name: Makah to IPA
    rules_path: myh_to_ipa.csv
    rule_ordering: apply-longest-first
    language_name: Makah
    in_lang: myh
    out_lang: myh-ipa
    case_sensitive: false
    authors:
      - David Huggins-Daines
```
And `myh_to_ipa.csv` (omitted, but you can see it in #355 ), when running `g2p generate-mapping --ipa myh` (after running `g2p update`, etc, *sigh*), I get this entry (trimmed slightly) in `g2p/mappings/langs/generated/config-g2p.yaml`:
```yaml
  - display_name: myh-ipa IPA to eng-ipa IPA
    in_lang: myh-ipa
    language_name: myh-ipa
    out_lang: eng-ipa
    rules_path: myh_to_ipa.csv
```
But the actual file that it generated is called `myh-ipa_to_eng-ipa.json`.  It's not even a CSV ;-)
